<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <AssemblyName>MacroSupremes</AssemblyName>
    <RootNamespace>MacroSupremes</RootNamespace>
    <Nullable>enable</Nullable>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.10.0</Version>
    <FileVersion>1.10.0.0</FileVersion>
    <Company>Supremes Guild</Company>
    <Product>Macro Supremes</Product>
    <Description>Automacao de mouse e teclado para WYD Global</Description>
    <Copyright>Supremes Guild 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Update="brasao.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
